apiVersion: proxy.igordc.com/v1alpha1
kind: ProxyDef
metadata:
  labels:
    app.kubernetes.io/name: proxydef
    app.kubernetes.io/instance: proxydef-sample
    app.kubernetes.io/part-of: proxius
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: proxius
  name: proxydef
spec:
  httpProxy: "http://proxy-us.intel.com:912"
  httpsProxy: "http://proxy-us.intel.com:912"
  noProxy: "localhost,127.0.0.1,.intel.com,.svc,.local,.cluster,10.0.0.0/16,192.168.0.0/16,172.17.0.1"
